#!/bin/bash
case $(cat /home/ali/.i3/i3_layout) in
    default)    i3-msg layout stacking; echo "stacking" > /home/ali/.i3/i3_layout    ;;
    stacking)   i3-msg layout tabbed; echo "tabbed" > /home/ali/.i3/i3_layout        ;;
    *)          i3-msg layout default; echo "default" > /home/ali/.i3/i3_layout      ;;
esac
